# Generated by Django 5.1.3 on 2024-12-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance_tracker.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_tracker.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_tracker.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=1001),
        ),
    ]
