# Generated by Django 5.1.3 on 2024-12-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_remove_account_user_id_remove_transaction_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user_id',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_tracker.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_tracker.user'),
            preserve_default=False,
        ),
    ]
