# Generated by Django 5.1.3 on 2024-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
